# Generated by Django 6.1.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="min_baggage_weight",
            field=models.PositiveIntegerField(
                default=2,
                help_text=(
                    "Minimum baggage weight allowed for one passenger, kg."
                ),
            ),
        ),
        migrations.AddField(
            model_name="airplane",
            name="max_baggage_weight",
            field=models.PositiveIntegerField(
                default=10,
                help_text=(
                    "Maximum baggage weight allowed for one passenger, kg."
                ),
            ),
        ),
    ]
