# Generated by Django 6.1.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
        ("flights", "0002_add_baggage_weight_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="baggage_weight",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (2, "Up to 2 kg"),
                    (5, "Up to 5 kg"),
                    (10, "Up to 10 kg"),
                ],
                default=2,
            ),
        ),
    ]
